### ISSUE TITLE
Change scrollwheel-action name on teleport flags

### ISSUE THREAD

**Issue by Jmaster9999** [Task-Force-Red/Operation-Golden-Sands#10]
Change the name of the action on the teleport flags to the airfield. Currently they both say 'Teleport to LocationName'. To change the name you need to edit the first string in the array: `this addaction ["EDIT THIS",<other shit>];`

**Comment by Iowafarmer** [comment]
Should Be Fixed

**Comment by coachwn** [comment]
You don't close it until it is verified that it is fixed.

**Comment by Jmaster9999** [comment]
DId you test it in single player Iowa? If so, that means that it is verified to work and you need to specify that when you close the issue.

**Comment by Jmaster9999** [comment]
Tested, confirmed fixed.
