### ISSUE TITLE
Setup/Fix Zeus Slots

### ISSUE THREAD

**Issue by Jmaster9999** [Task-Force-Red/Operation-Golden-Sands#11]
Is Zeus accessible by a logged in admin?
(#adminLogged)

Are Zeus slots setup via Steamid for the following People?
Jebidah: 76561197989531615
Nichols: 76561198008394100
ScottyZ: 76561198245991184
IowaFarmer: 76561198073566898

**Comment by Jmaster9999** [comment]
Done

**Comment by Scotty-Z** [comment]
yes checked the mission that is on GitHub

**Comment by coachwn** [comment]
Where is the one that is needed for #adminLogged?

**Comment by Scotty-Z** [comment]
Unless one one deleted it it shoud be thhe first on one the left side

**Comment by Jmaster9999** [comment]
AdminLogged Zeus Slot is working. Can the other people listed test their slots?

**Comment by coachwn** [comment]
Nichols Zeus slot is not working as of right now. Have restarted and relogged and it is not working.

**Comment by coachwn** [comment]
So slot started working but why does it do this...possible BI problem/feature.

**Comment by Jmaster9999** [comment]
Yeah, Zeus has always been a littlebit fucky. Apparently it happens when you connect while somone is in zeus, not 100% sure on that though. It's most definitely a BI issue though, unless the ACE Zeus module or AREs are somehow breaking things.
