### ISSUE TITLE
M203 Sights/Resets after every firing

### ISSUE THREAD

**Issue by KingHeavy** [Task-Force-Red/Operation-Golden-Sands#12]
The M203 sights on the M4's are blocked by the silencer, and every time you fire the M203 it resets to semi-auto on the rifle.

**Comment by coachwn** [comment]
NIArms issue...will not be able to fix until they do it. We need to report to NIArms.

**Comment by coachwn** [comment]
Was just informed this was an RHS weapon...will reopen.

**Comment by KingHeavy** [comment]
Perhaps seeing as we already have one slot using the mk 18, my not just use the mk 18 with the 320. May not be pretty, but it works.

**Comment by Jmaster9999** [comment]
The issue with the m320 sight also happens with the mk18. The m320 is usuable, however when you range beyond 250m it bugs out,.  This appears to be an RHS bug,but further testing with just RHS and ACE would be required.
