### ISSUE TITLE
Disable alive logisitics on FOB base parts

### ISSUE THREAD

**Issue by Jmaster9999** [Task-Force-Red/Operation-Golden-Sands#16]
Make sure that players cannot pickup the walls of the FOB... 
Possibly ways to do this:
- Set the base walls as 'Simple Objects'
- Disable moving those walls with Alive Logistics?

**Comment by coachwn** [comment]
Changed to a later milestone since it isn't a critical fix at this point.

**Comment by Scotty-Z** [comment]
Alive logistics should be disabled as we are not building nor moving tghings around

**Comment by coachwn** [comment]
Should already be done per @Iowafarmer last update that I pushed to the server.
