### ISSUE TITLE
Clothes floating in air on restart with no weapons

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Operation-Golden-Sands#17]
After using player exit and logging out and then restarting Arma came back in to test the Zeus slot I got a config error on loading and came in without clothes on, no weapons, helmet or any other gear. Backpack/vest was floating in air beside my character. Possible problem with Military Gear Pack.

**Comment by Jmaster9999** [comment]
Miliary gear pack may be causing this issue.

**Comment by Iowafarmer** [comment]
I have not seen this problem until yesterday. Scotty and I will look into it.

**Comment by Jmaster9999** [comment]
Possibly related to #18
