### ISSUE TITLE
Multiple reports of people getting off MH6 little bird with no clothes on but...

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Operation-Golden-Sands#18]
On my front end I still had clothes on but Ronin did not have any on. All he did was get off a little bird that I spawned in to fly us back out of the AO after successfully rescuing Jrod. 

Pictures to follow tomorrow.

**Comment by Jmaster9999** [comment]
Possibly related to issue #17 ?

**Comment by Iowafarmer** [comment]
First time the problem has ever happened. We have used little birds and black hawks in all previous tests with no gear issues.

**Comment by FordJMTFR** [comment]
Could it be because of the Uniform pack?

**Comment by Scotty-Z** [comment]
Didn't have this problem on my deployment and we use the uniform pack

**Comment by Scotty-Z** [comment]
I'm going to say it was a bug with thing not syncing up right there was a massive lag spike when yoku guys were flying

**Comment by coachwn** [comment]
Think the lag might have been related to the spawning of AI into the area where we loaded into the helo we spawned in.
