### ISSUE TITLE
T6 Texan is out of date, and has multiple issues

### ISSUE THREAD

**Issue by Jmaster9999** [Task-Force-Red/Operation-Golden-Sands#19]
I'm we should remove the T6. It has reflection issues with the cockpit, a non-functional gyrocam (No terrain track), an out-dated flight model and a broken damage model.

Reflection issue images (Minor but annoying):
https://steamuserimages-a.akamaihd.net/ugc/896637749302223287/0234E10C401C66E651894BDA1A17CADCC685316B/

https://steamuserimages-a.akamaihd.net/ugc/896637749302223745/AFBA831DE1B3B985509783ACE777A0CFC25E340E/

Damage model errors (Damage model out of date):
https://steamuserimages-a.akamaihd.net/ugc/896637749302314689/E5498AA856619F50663B348B5B889F69604E7994/

- Small arms fire does no damage to the aircraft.
- Damage does not get applied to the aircraft/it's parts, it gets removed from a HP cap.
- The aircraft is either flying or destroyed, there is no partial damage. You cannot lose your engine, instruments or flight controls.
- If you get hit by an AA missile you either take no damage at all, or instantly die.
- Damage is a set cap: you can be 1 shot from being destroyed but there is no effect on the aircraft until you get shot, where you instantly explode.

**Comment by Scotty-Z** [comment]
We talked about this if it's such a big problem Have it removed from the mission

**Comment by Iowafarmer** [comment]
May I suggest PILOT TRAINING....

**Comment by Jmaster9999** [comment]
The aircraft has a broken damage model. Rockets, Mk19s, .50cals, ZU-23s DO NOT do any damage.

**Comment by coachwn** [comment]
Change aircraft to something from RHS due to landing bug which has issues with landing of T-6 if it has damage. Damage is not reported via hitpoints to the pilot so you have no clue if it is damaged until you blow up on landing.

**Comment by coachwn** [comment]
Replaced with RHS L159 in mission...moving on now.
