### ISSUE TITLE
Military Gear Pack possible issues

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Operation-Golden-Sands#21]
Investigate possible issues with Military Gear Pack.  Tasks to follow:

- [x] Test loadout in multiplayer with vanilla uniforms and TF Red Utils.
- [x] Test loadout in multiplayer with VSM uniforms, vests and backpacks with TF Red Utils.
- [ ] Test loadout in multiplayer with MilGearPack, ACE, ALiVE, TF Red Utils and CBA only.
- [x] Report test results in this thread.

**Comment by Jmaster9999** [comment]
Maybe causing issues #18 and #17 (Floating gear and losing clothes exiting helos)

**Comment by coachwn** [comment]
Its not VSM for sure...its an issue from BI when people spawn without clothes. Server performance is significantly better without floating backpacks from MilGearPack. Still investigating what the problem might be.

Also @Iowafarmer don't go jumping around like a mexican jumping bean and the little chicken screaming about the sky falling for now reason.

**Comment by coachwn** [comment]
Tested MilGP with vanilla and TF Red Utils and had floating backpacks as well.
Tested VSM setup and did not get floating backpacks.
Did not test in #3 on the list above as I ran out of time.
