### ISSUE TITLE
no earplugs for pilots

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Operation-Golden-Sands#22]
This was reported by DeGone due to going deaf while launching rockets and flying around.

**Comment by Iowafarmer** [comment]
Added earplugs. Thought their helmets replaced earplugs for them?

**Comment by Jmaster9999** [comment]
They are but ears still ring from firing weapons. It's wierd...

**Comment by coachwn** [comment]
It depends on whoseveral assets are being used. Some helmets don't have the earplugs action and some do.

**Comment by Jmaster9999** [comment]
Implemented
