### ISSUE TITLE
Change Pylon Weapons to gunner

### ISSUE THREAD

**Issue by Jmaster9999** [Task-Force-Red/Operation-Golden-Sands#24]
- Weapons on pylons are set to pilot which bugs out the locking/laser.
- M134 should be for pilot, Guided missiles for gunner
- To change the pylon user: Click on the Driver symbol and change it to the Gunner symbol.

**Comment by Iowafarmer** [comment]
For the Black Hawks should it also be set to gunner? There is no Co-Pilot option but 2  Gunner options if I remember correctly

**Comment by Jmaster9999** [comment]
No, not the blackhawks. For some reason it can bug out and give the weapons options to one of the passengers. Also, since the blackhawks don't have a laserpod it would be better for the pilot to have control of the missiles so they can aim them if needed.

**Comment by Jmaster9999** [comment]
Fix the Pylon blackhawks.... I said not to change the weapons on them, make the weapons for the pilots seat otherwise it bugs out and gives them to a random passenger...

**Comment by coachwn** [comment]
Closed...couldn't fix it appropriately.
