### ISSUE TITLE
Few items inside your mission structure need to be addressed.

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Operation-Golden-Sands#4]
- [x] Allow everyone to be able to repair vehicles and not just "Engineer" types.
- [x] Change TFAR channel name to reflect accurate name in the Teamspeak channel listing.
- [x] Might want to check your OPFOR Mil Logistics to only faction and not side and faction or you will have CSAT controlled aircraft coming into the mission to attack BLUFOR (players) at a regular occurence.
- [x] Is Tali_Opfor supposed to be assymetric and having aircraft available to them for resupply and assistance?
- [x] Suggest you lower CUP_TAK civ spawn radius for helos to 500-600 or you will have items spawning all over map if teams are split up and helos are flying.
- [x] @Iowafarmer you have to remove the ALiVE Weather module...it is a major known conflict with ACE Weather and creates problems with winds that move all vehicles and aircraft and tosses them around map. Also it does not work with ACE Balllistics.
- [x] @Iowafarmer you have 2 instances of ALiVE Civilian Population module placed down. One instance is synced to the ALiVE Civilian Placement module which is good and the other is by the ALiVE weather module and is not necessary.
- [x] Why no IED Detection Alert in the ALiVE IED module with the Mine Detector as the tool to detect mines?
- [x] Why aren't SF teams grouped together into one unit and why is the pilot leader not with the pilots?
- [x] WTF....Leights OPFOR/Project OPFOR????? With all the CUP Factions that AuburnAlumni has we have to deal with that POS still.
- [x] Base location on the sloping area? Vehicles (helicopters) started sliding down slope when I got in them...have you had this happen before? Made for extremely difficult take off in cramped quarters.

**Comment by Iowafarmer** [comment]
Most Issues have been fixed. Project Opfor has never been in this mission though so alittle confused on that.

**Comment by coachwn** [comment]
There is a LOPS_OPFOR classname I found in the mission file earlier today. Didn't write down which one it's located in though.

**Comment by Iowafarmer** [comment]
That is odd. I have never launched that mission with project opfor.
