### ISSUE TITLE
Test server now up on on the main box for testing.

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Operation-Golden-Sands#5]
Make sure you guys jump on it...server pw and port are available from Iowa and or Scotty.

**Comment by coachwn** [comment]
Has anyone tested the version that was uploaded on Sunday 24 September?

If not why?

If so what things need to be adjusted/tweaked and ready for implementation?

**Comment by Jmaster9999** [comment]
Mission is currently being tested, as of 5pm PST on the 26th.

**Comment by coachwn** [comment]
Closing...and yes the labels are needed.
