### ISSUE TITLE
Adjustment of TAOR's for Mil Placement Civ Object and reduction of overall objectives.

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Operation-Golden-Sands#6]
Working to adjust and tweak the settings on the objectives. In the OPCOM it is showing almost 350+ objectives on the map in its current state. The version I have running now on my box is under 290 objectives and it still needs to be adjusted further.

**Comment by coachwn** [comment]
From Jeb - "Enlarge blacklist around base area on the main part because we are still getting random AI moving into the base area"

**Comment by Jmaster9999** [comment]
Created a new issue for Jeb's comment

**Comment by coachwn** [comment]
Items are already completed unless there has been a new development since the last version was pushed to the server.
