### ISSUE TITLE
Mission Narrative and Weekend Operations

### ISSUE THREAD

**Issue by Jmaster9999** [Task-Force-Red/Operation-Golden-Sands#7]
Can we have a meeting to discuss and write out a mission narrative complete with a rough idea of the large weekend ops? If you have an big ideas or weekend-ops you want to run it would be a good idea to get them all written down. Examples of mission narrative events are: an event with an embassy, IDAP, or a natural disaster.

**Comment by coachwn** [comment]
Going to remove you from this one Jmaster as it needs to be between Jebudiah, Scotty and Iowa to come up with the details.

Thanks for posting.

**Comment by Jmaster9999** [comment]
Iowa mentioned that he wanted to talk to me about mission ideas, and I was going to facilitate the meeting.

**Comment by Jmaster9999** [comment]
Meeting finished. Also, you only need 1 severity tag, not all of them. Marking something as Critical and High Priority doesn't make it get fixed any faster, it just means more tags.

**Comment by coachwn** [comment]
If I want to add 100 severity tags to it that is what I will do.
