### ISSUE TITLE
Enlarge Base Blacklist

### ISSUE THREAD

**Issue by Jmaster9999** [Task-Force-Red/Operation-Golden-Sands#8]
Enlarge the base blacklist to cover the surrounding towns to prevent random AI patrols from coming near the base. During the first weekend-op, we could populate the surrounding towns with Zeus so that players still have to clear them. 

Created a new issue from this comment by 
Nichols: 
> From Jeb - "Enlarge blacklist around base area on the main part because we are still getting random AI moving into the base area"

**Comment by coachwn** [comment]
This was already done in the version that is on the server. I did it on Sunday 24 September.
