### ISSUE TITLE
Add TAORs to cover airfields or add custom Objectives

### ISSUE THREAD

**Issue by Jmaster9999** [Task-Force-Red/Operation-Golden-Sands#9]
Add a TAOR to cover Al Vegh and the airfield next to it, since currently ai is not spawning in that area. Additionally the other airfields on the map do not have any ai assigned to them. Either they don't have objectives or the priority isn't high enough.

**Comment by coachwn** [comment]
Suggested to @Iowafarmer to update mission with custom objectives...should already be done by the time this post is being written. Also gave information on how to update and utilize custom objectives on the map.

For the record AL RAYAK sucks monkey balls that are still attached to a jungle monkey in the Congo.

**Comment by Iowafarmer** [comment]
Fixed

**Comment by coachwn** [comment]
New mission file or one I uploaded Sunday?

**Comment by Jmaster9999** [comment]
Commit 05c3bc4 (17 hours ago) pushed a new mission file.

**Comment by Jmaster9999** [comment]
Airfields spawning appropriate amounts of enemy forces. Tested, confirmed working on the live server.
